### PR TITLE
Basic configuration for webpack, hot reload, etc etc

### PR DESCRIPTION
**Pull request by rafaelchiti**
@leoasis uploading this as WIP in case you wanna continue it, Im checking out now and will probably work on it tomorrow.

### CODE REVIEW

**Comment by leoasis** [comment]
I believe we want the dev server to be "mounted" in the real server right? So we don't have to have two servers, one for the api, another for webpack

**Comment by rafaelchiti** [comment]
Yeah make sense, if you remember how to do it then your help welcomed if not Ill dig around.

**Comment by rafaelchiti** [comment]
Don't remember how complicated this is, but I think it takes some tries to get that setup, is there other benefit besides not having to run locally two processes ?

**Comment by leoasis** [comment]
You can check this for a way to mount webpack into our server: https://github.com/gaearon/react-transform-boilerplate/blob/master/devServer.js

It uses webpack-dev-middleware instead of the devserver

**Comment by rafaelchiti** [comment]
Ok will time box it, was just wondering if everything would work out of the box, will give it a try.

**Comment by rafaelchiti** [comment]
Actually I would rather merge this and improve that in parallel so I can work on components meanwhile. @leoasis thoughts?

**Comment by leoasis** [comment]
ok sure! I can work on that if you prefer 👍

**Comment by rafaelchiti** [comment]
Don't mind working on it but already gave it a quick try without luck so I know that for sure will take me an hour or more digging around the errors so rather make progress on other stuff and tackle this in parallel during some death slots in the day.

**Pull request merged**
